// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahyysoburxbhnjiekdwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoeXlzb2J1cnhiaG5qaWVrZHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NjgyNjQsImV4cCI6MjA2MDQ0NDI2NH0.WPCTXagyEz8fDcMCknoLgcJq2HjYFjxOJDUPa9lkgGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);